/// lib/db/schema.ts
export const TABLES = {
  USERS:                  "nextauth_users",
  ACCOUNTS: "nextauth_accounts",
  SESSIONS: "nextauth_sessions",
  VERIFICATION_TOKENS: "nextauth_verification_tokens",
  HEALTH_SNAPSHOTS: "health_snapshots",
  BIOMARKERS: "biomarkers",
  UPLOADS: "uploads",
  PROTOCOLS: "protocols",
  BOOKMARKS: "bookmarks",
  CHECKIN_RESPONSES: "checkin_responses",
  // Ingestion pipeline (migration 001)
  HEALTH_UPLOADS: "health_uploads",
  WEARABLE_SNAPSHOTS: "wearable_snapshots",
  PROTOCOL_OUTPUTS: "protocol_outputs",
  RATE_LIMIT_BUCKETS: "rate_limit_buckets",
  // Wearable OAuth (migration 003)
  WEARABLE_CONNECTIONS: "wearable_connections",
  // Sports event prep (migration 005)
  SPORTS_PROTOCOLS: "sports_protocols",
  // Health goal prep packs (migration 007)
  GOAL_PROTOCOLS: "goal_protocols",
  // Supplement adoption events (migration 008)
  USER_SUPPLEMENT_ADOPTIONS: "user_supplement_adoptions",
  // Onboarding profiles (migration 009)
  PROFILES: "profiles",
  // Referral + partners (migration 010)
  REFERRAL_LINKS:       "referral_links",
  REFERRAL_CONVERSIONS: "referral_conversions",
  TRAINING_PARTNERS:    "training_partners",
  // Analysis reports + API usage (migration 014)
  ANALYSIS_REPORTS:     "analysis_reports",
  API_USAGE:            "api_usage",
  // Wearable upload event tracking (migration 016)
  WEARABLE_UPLOAD_EVENTS: "wearable_upload_events",
  // Recommendation engine (migration 018)
  HEALTH_PRODUCTS:              "health_products",
  USER_HEALTH_CONTEXT:          "user_health_context",
  DOSING_RULES:                 "dosing_rules",
  PROTOCOL_SNAPSHOTS:           "protocol_snapshots",
  PRODUCT_PERFORMANCE_SIGNALS:  "product_performance_signals",
  SUPPLEMENT_ADHERENCE_LOG:     "supplement_adherence_log",
  NOTIFICATION_LOG:             "notification_log",
  PRACTITIONER_ACCESS:          "practitioner_access",
  // Consent & research (migration 018)
  CONSENT_RECORDS:                  "consent_records",
  CONSENT_AUDIT_LOG:                "consent_audit_log",
  CONSENT_VERSION_HISTORY:          "consent_version_history",
  RESEARCH_COHORTS:                 "research_cohorts",
  COHORT_ENROLLMENTS:               "cohort_enrollments",
  DEIDENTIFIED_BIOMARKER_RESEARCH:  "deidentified_biomarker_research",
  // v8 clinical tables (migration 018)
  CRITICAL_VALUE_THRESHOLDS:        "critical_value_thresholds",
  CRITICAL_VALUE_EVENTS:            "critical_value_events",
  PREGNANCY_SAFETY_RULES:           "pregnancy_safety_rules",
  NUTRIENT_COMPETITION_RULES:       "nutrient_competition_rules",
  ADVERSE_EVENT_REPORTS:            "adverse_event_reports",
  ADVERSE_EVENT_AGGREGATES:         "adverse_event_aggregates",
  ADVERSE_EVENT_PROMPTS:            "adverse_event_prompts",
  PERSONAL_BIOMARKER_BASELINES:     "personal_biomarker_baselines",
  PERSONAL_BASELINE_HISTORY:        "personal_baseline_history",
  TRAINING_PHASE_DETECTIONS:        "training_phase_detections",
  PROTOCOL_PDF_EXPORTS:             "protocol_pdf_exports",
  OUTCOME_MILESTONES:               "outcome_milestones",
  OUTCOME_SUMMARIES:                "outcome_summaries",
  // V7 feature tables (migration 019)
  PRODUCT_FORMS:                    "product_forms",
  USER_MEDICATIONS:                 "user_medications",
  DRUG_INTERACTION_RULES:           "drug_interaction_rules",
  MENSTRUAL_CYCLE_TRACKING:         "menstrual_cycle_tracking",
  CYCLE_PHASE_MODIFIERS:            "cycle_phase_modifiers",
  NOTIFICATION_PREFERENCES:         "notification_preferences",
  PROTOCOL_RAMP_PLANS:              "protocol_ramp_plans",
  PROTOCOL_RAMP_STEPS:              "protocol_ramp_steps",
  SUPPLEMENT_CYCLES:                "supplement_cycles",
  CUMULATIVE_DOSE_SAFETY:           "cumulative_dose_safety",
  NUTRIENT_UPPER_LIMITS:            "nutrient_upper_limits",
  USER_SUPPLY_TRACKING:             "user_supply_tracking",
  SYMPTOM_REPORTS:                  "symptom_reports",
  SYMPTOM_MARKER_MAP:               "symptom_marker_map",
  PROTOCOL_SIMULATIONS:             "protocol_simulations",
  PROTOCOL_SHARE_CARDS:             "protocol_share_cards",
  CHRONOTYPE_TIMING_OFFSETS:        "chronotype_timing_offsets",
  USER_PROTOCOL_TIMELINES:          "user_protocol_timelines",
  TRAVEL_EVENTS:                    "travel_events",
  FOUNDING_APPLICATIONS:            "founding_applications",
} as const;

export type TableName = (typeof TABLES)[keyof typeof TABLES];

export const COLS = {
  ID: "id",
  USER_ID: "user_id",
  CREATED_AT: "created_at",
  UPDATED_AT: "updated_at",
  EMAIL: "email",
  NAME: "name",
  IMAGE: "image",
  EMAIL_VERIFIED: "email_verified",
  PLAN: "plan",
  FILE_NAME: "file_name",
  FILE_SIZE: "file_size",
  MIME_TYPE: "mime_type",
  STORAGE_PATH: "storage_path",
  PARSE_STATUS: "parse_status",
  STATUS: "status",
  MODE: "mode",
  SELECTED_AGE: "selected_age",
  GOALS: "goals",
  BUDGET: "budget",
  PREFERENCES: "preferences",
  PAYLOAD: "payload",
  VERSION: "version",
  TRIGGER_REASON: "trigger_reason",
  SHARE_TOKEN: "share_token",
  SHARE_TOKEN_EXPIRES_AT: "share_token_expires_at",
  ERROR_MESSAGE: "error_message",
  ITEM_ID: "item_id",
  CATEGORY: "category",
  PROTOCOL_ID: "protocol_id",
  WEEK_NUMBER: "week_number",
  RESPONSES: "responses",
  SNAPSHOT_ID: "snapshot_id",
  VALUE: "value",
  UNIT: "unit",
  REFERENCE_MIN: "reference_min",
  REFERENCE_MAX: "reference_max",
  SOURCE: "source",
  DATE: "date",
  RAW_DATA: "raw_data",
  PARSED_DATA: "parsed_data",
  // Ingestion pipeline (migration 001)
  UPLOAD_ID: "upload_id",
  WARNINGS: "warnings",
  PRIORITY_SCORE: "priority_score",
  MODEL: "model",
  RAW_RESPONSE: "raw_response",
  PARSED_OUTPUT: "parsed_output",
  INPUT_TOKENS: "input_tokens",
  OUTPUT_TOKENS: "output_tokens",
  ENDPOINT: "endpoint",
  WINDOW_START: "window_start",
  REQUEST_COUNT: "request_count",
  // wearable_connections (migration 003)
  PROVIDER: "provider",
  PROVIDER_USER_ID: "provider_user_id",
  EXPIRES_AT: "expires_at",
  SCOPE: "scope",
  ACCESS_TOKEN: "access_token",
  REFRESH_TOKEN: "refresh_token",
  CONNECTED_AT: "connected_at",
  HRV: "hrv",
  RESTING_HR: "resting_hr",
  SLEEP_SCORE: "sleep_score",
  DEEP_SLEEP_MIN: "deep_sleep_min",
  REM_SLEEP_MIN: "rem_sleep_min",
  RECOVERY_SCORE: "recovery_score",
  STRAIN_SCORE: "strain_score",
  READINESS_SCORE: "readiness_score",
  STEPS: "steps",
  ACTIVE_CALORIES: "active_calories",
  // onboarding (migration 004)
  ONBOARDING_GOALS:         "onboarding_goals",
  ONBOARDING_WEARABLE_DONE: "onboarding_wearable_done",
  // sports_protocols (migration 005)
  COMPETITION_TYPE:         "competition_type",
  EVENT_DATE:               "event_date",
  WEEKS_TO_EVENT:           "weeks_to_event",
  PRIORITY_OUTCOME:         "priority_outcome",
  EXPERIENCE_LEVEL:         "experience_level",
  GENDER:                   "gender",
  AGE:                      "age",
  CURRENT_INJURIES:         "current_injuries",
  KNOWN_CONDITIONS:         "known_conditions",
  MEDICATIONS:              "medications",
  STIMULANT_TOLERANCE:      "stimulant_tolerance",
  BUDGET_VALUE:             "budget_value",
  BUDGET_TIER:              "budget_tier",
  RACE_DISTANCE:            "race_distance",
  PROTOCOL_GENERATED_AT:    "protocol_generated_at",
  // goal_protocols (migration 007)
  CATEGORY_DATA:            "category_data",
  // user_supplement_adoptions (migration 008)
  SUPPLEMENT_NAME:          "supplement_name",
  ADOPTED_AT:               "adopted_at",
  PROTOCOL_TYPE:            "protocol_type",
  // profiles (migration 009 + 011 + 017)
  PRIMARY_GOAL:             "primary_goal",
  SECONDARY_GOAL:           "secondary_goal",
  SECONDARY_GOAL_SET_AT:    "secondary_goal_set_at",
  ONBOARDING_COMPLETED_AT:  "onboarding_completed_at",
  ONBOARDING_STEP:          "onboarding_step",
  AVATAR_URL:               "avatar_url",
  TAGLINE:                  "tagline",
  LOCATION:                 "location",
  PRS:                      "prs",
  PROFILE_NUDGE_DISMISSED:  "profile_nudge_dismissed",
  // profiles — biological age (migration 012)
  BIOLOGICAL_AGE:           "biological_age",
  BIOLOGICAL_AGE_DELTA:     "biological_age_delta",
  BIO_AGE_PERCENTILE:       "bio_age_percentile",
  BIO_AGE_CALCULATED_AT:    "bio_age_calculated_at",
  BIO_AGE_CONFIDENCE:       "bio_age_confidence",
  BIO_AGE_REVEALED:         "bio_age_revealed",
  BIO_AGE_DRIVERS:          "bio_age_drivers",
  // referral_links + referral_conversions (migration 010)
  CODE:                     "code",
  CLICKS:                   "clicks",
  CONVERSIONS:              "conversions",
  REFERRER_ID:              "referrer_id",
  REFEREE_ID:               "referee_id",
  CONVERTED_AT:             "converted_at",
  // training_partners (migration 010)
  PARTNER_USER_ID:          "partner_user_id",
  INVITE_TOKEN:             "invite_token",
  PARTNER_NAME:             "partner_name",
  PARTNER_EMAIL:            "partner_email",
  ACCEPTED_AT:              "accepted_at",
  // Terra wearable integration (migration 013)
  TERRA_USER_ID:            "terra_user_id",
  RECORDED_AT:              "recorded_at",
  HEART_RATE_RESTING:       "heart_rate_resting",
  HEART_RATE_AVG:           "heart_rate_avg",
  HEART_RATE_MAX:           "heart_rate_max",
  HRV_RMSSD:                "hrv_rmssd",
  SLEEP_TOTAL_MINUTES:      "sleep_total_minutes",
  SLEEP_REM_MINUTES:        "sleep_rem_minutes",
  SLEEP_DEEP_MINUTES:       "sleep_deep_minutes",
  SLEEP_LIGHT_MINUTES:      "sleep_light_minutes",
  VO2_MAX:                  "vo2_max",
  STRESS_SCORE:             "stress_score",
  SPO2:                     "spo2",
  RAW_PAYLOAD:              "raw_payload",
  // analysis_reports + api_usage (migration 014)
  REPORT_TYPE:              "report_type",
  INPUT_SNAPSHOT:           "input_snapshot",
  GENERATED_AT:             "generated_at",
  DURATION_MS:              "duration_ms",
  COST_USD:                 "cost_usd",
  // api_usage — per-stage analysis detail (migration 015)
  STAGE_2_INPUT_TOKENS:     "stage_2_input_tokens",
  STAGE_2_OUTPUT_TOKENS:    "stage_2_output_tokens",
  STAGE_3_INPUT_TOKENS:     "stage_3_input_tokens",
  STAGE_3_OUTPUT_TOKENS:    "stage_3_output_tokens",
  DEPTH_LEVEL:              "depth_level",
  DATA_COMPLETENESS:        "data_completeness",
  // profiles — biomarker engine additions (migration 014)
  BIOLOGICAL_SEX:           "biological_sex",
  HEIGHT_CM:                "height_cm",
  WEIGHT_KG:                "weight_kg",
  ACTIVITY_LEVEL:           "activity_level",
  ATHLETE_ARCHETYPE:        "athlete_archetype",
  HEALTH_GOALS:             "health_goals",
  CURRENT_MEDICATIONS:      "current_medications",
  CURRENT_SUPPLEMENTS:      "current_supplements",
  CONDITIONS:               "conditions",
  USER_TIER:                "user_tier",
  // wearable upload events + profile freshness (migration 016)
  SCENARIO:                     "scenario",
  LAST_WEARABLE_UPLOAD_AT:      "last_wearable_upload_at",
  BASELINE_ESTABLISHED_AT:      "baseline_established_at",
} as const;

export const BUCKETS = {
  HEALTH_FILES: "health-files",
} as const;

export type Plan = "free" | "pro" | "clinic";
export type WearableSource = "whoop" | "oura" | "garmin" | "apple_health" | "samsung_galaxy_watch";
export type UploadSource = WearableSource | "pdf";
