/// lib/db/schema.ts
export const TABLES = {
  USERS:                  "nextauth_users",
  ACCOUNTS: "nextauth_accounts",
  SESSIONS: "nextauth_sessions",
  VERIFICATION_TOKENS: "nextauth_verification_tokens",
  HEALTH_SNAPSHOTS: "health_snapshots",
  BIOMARKERS: "biomarkers",
  UPLOADS: "uploads",
  PROTOCOLS: "protocols",
  BOOKMARKS: "bookmarks",
  CHECKIN_RESPONSES: "checkin_responses",
  // Ingestion pipeline (migration 001)
  HEALTH_UPLOADS: "health_uploads",
  WEARABLE_SNAPSHOTS: "wearable_snapshots",
  PROTOCOL_OUTPUTS: "protocol_outputs",
  RATE_LIMIT_BUCKETS: "rate_limit_buckets",
  // Wearable OAuth (migration 003)
  WEARABLE_CONNECTIONS: "wearable_connections",
  // Sports event prep (migration 005)
  SPORTS_PROTOCOLS: "sports_protocols",
  // Health goal prep packs (migration 007)
  GOAL_PROTOCOLS: "goal_protocols",
} as const;

export type TableName = (typeof TABLES)[keyof typeof TABLES];

export const COLS = {
  ID: "id",
  USER_ID: "user_id",
  CREATED_AT: "created_at",
  UPDATED_AT: "updated_at",
  EMAIL: "email",
  NAME: "name",
  IMAGE: "image",
  EMAIL_VERIFIED: "email_verified",
  PLAN: "plan",
  FILE_NAME: "file_name",
  FILE_SIZE: "file_size",
  MIME_TYPE: "mime_type",
  STORAGE_PATH: "storage_path",
  PARSE_STATUS: "parse_status",
  STATUS: "status",
  MODE: "mode",
  SELECTED_AGE: "selected_age",
  GOALS: "goals",
  BUDGET: "budget",
  PREFERENCES: "preferences",
  PAYLOAD: "payload",
  VERSION: "version",
  TRIGGER_REASON: "trigger_reason",
  SHARE_TOKEN: "share_token",
  SHARE_TOKEN_EXPIRES_AT: "share_token_expires_at",
  ERROR_MESSAGE: "error_message",
  ITEM_ID: "item_id",
  CATEGORY: "category",
  PROTOCOL_ID: "protocol_id",
  WEEK_NUMBER: "week_number",
  RESPONSES: "responses",
  SNAPSHOT_ID: "snapshot_id",
  VALUE: "value",
  UNIT: "unit",
  REFERENCE_MIN: "reference_min",
  REFERENCE_MAX: "reference_max",
  SOURCE: "source",
  DATE: "date",
  RAW_DATA: "raw_data",
  PARSED_DATA: "parsed_data",
  // Ingestion pipeline (migration 001)
  UPLOAD_ID: "upload_id",
  WARNINGS: "warnings",
  PRIORITY_SCORE: "priority_score",
  MODEL: "model",
  RAW_RESPONSE: "raw_response",
  PARSED_OUTPUT: "parsed_output",
  INPUT_TOKENS: "input_tokens",
  OUTPUT_TOKENS: "output_tokens",
  ENDPOINT: "endpoint",
  WINDOW_START: "window_start",
  REQUEST_COUNT: "request_count",
  // wearable_connections (migration 003)
  PROVIDER: "provider",
  PROVIDER_USER_ID: "provider_user_id",
  EXPIRES_AT: "expires_at",
  SCOPE: "scope",
  ACCESS_TOKEN: "access_token",
  REFRESH_TOKEN: "refresh_token",
  CONNECTED_AT: "connected_at",
  HRV: "hrv",
  RESTING_HR: "resting_hr",
  SLEEP_SCORE: "sleep_score",
  DEEP_SLEEP_MIN: "deep_sleep_min",
  REM_SLEEP_MIN: "rem_sleep_min",
  RECOVERY_SCORE: "recovery_score",
  STRAIN_SCORE: "strain_score",
  READINESS_SCORE: "readiness_score",
  STEPS: "steps",
  ACTIVE_CALORIES: "active_calories",
  // onboarding (migration 004)
  ONBOARDING_GOALS:         "onboarding_goals",
  ONBOARDING_WEARABLE_DONE: "onboarding_wearable_done",
  // sports_protocols (migration 005)
  COMPETITION_TYPE:         "competition_type",
  EVENT_DATE:               "event_date",
  WEEKS_TO_EVENT:           "weeks_to_event",
  PRIORITY_OUTCOME:         "priority_outcome",
  EXPERIENCE_LEVEL:         "experience_level",
  GENDER:                   "gender",
  AGE:                      "age",
  CURRENT_INJURIES:         "current_injuries",
  KNOWN_CONDITIONS:         "known_conditions",
  MEDICATIONS:              "medications",
  STIMULANT_TOLERANCE:      "stimulant_tolerance",
  BUDGET_VALUE:             "budget_value",
  BUDGET_TIER:              "budget_tier",
  RACE_DISTANCE:            "race_distance",
  PROTOCOL_GENERATED_AT:    "protocol_generated_at",
  // goal_protocols (migration 007)
  CATEGORY_DATA:            "category_data",
} as const;

export const BUCKETS = {
  HEALTH_FILES: "health-files",
} as const;

export type Plan = "free" | "pro" | "clinic";
export type WearableSource = "whoop" | "oura" | "garmin" | "apple_health";
export type UploadSource = WearableSource | "pdf";
