/// lib/blood-test/generate-doctor-letter.ts
// Client-only — uses jsPDF which requires a browser environment.

import type { DetectionResult } from "./detect-missing-markers";
import type { BiomarkerCategory } from "./biomarker-registry";

export async function generateDoctorLetterPDF(detection: DetectionResult): Promise<void> {
  // Dynamic import keeps jsPDF out of the server bundle
  const { jsPDF } = await import("jspdf");

  const doc  = new jsPDF();
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  // ── HEADER ──────────────────────────────────────────────────────────────────
  doc.setFontSize(20);
  doc.setTextColor(30, 30, 30);
  doc.text("Blood Test Request — Blue Zone Protocol", 20, 25);

  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated ${date} · bluezone.app`, 20, 33);

  doc.setDrawColor(220, 220, 220);
  doc.line(20, 38, 190, 38);

  // ── INTRO ────────────────────────────────────────────────────────────────────
  doc.setFontSize(11);
  doc.setTextColor(50, 50, 50);
  const intro = [
    "Dear Doctor,",
    "",
    "My health optimization platform (Blue Zone) has analyzed my recent blood test and",
    "identified several biomarkers that would significantly improve the accuracy of my",
    "personalized protocol. I would be grateful if you could include the following tests",
    "in my next blood panel.",
  ];
  let y = 50;
  for (const line of intro) { doc.text(line, 20, y); y += 6; }

  y += 4;

  // ── GROUPED MARKERS ──────────────────────────────────────────────────────────
  for (const [category, markers] of Object.entries(detection.missingByCategory) as [BiomarkerCategory, typeof detection.missingEssential][]) {
    // Dynamic import of CATEGORY_META to avoid circular issues if called separately
    const { CATEGORY_META } = await import("./biomarker-registry");
    const meta = CATEGORY_META[category];
    if (!meta || !markers?.length) continue;

    // Category heading
    doc.setFontSize(12);
    doc.setTextColor(80, 60, 160);
    doc.text(`${meta.icon}  ${meta.label}`, 20, y);
    y += 7;

    // Markers
    doc.setFontSize(10);
    for (const marker of markers) {
      doc.setTextColor(30, 30, 30);
      doc.setFont("helvetica", "bold");
      doc.text(`• ${marker.name}`, 26, y);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 100, 100);
      y += 5;

      const lines = doc.splitTextToSize(marker.whyItMatters, 155) as string[];
      for (const line of lines) { doc.text(line, 30, y); y += 5; }
      y += 3;
    }
    y += 4;

    // New page if needed
    if (y > 260) { doc.addPage(); y = 20; }
  }

  // ── FOOTER ───────────────────────────────────────────────────────────────────
  doc.setFontSize(9);
  doc.setTextColor(160, 160, 160);
  doc.text(
    "Generated by Blue Zone · bluezone.app · Personalized Health Optimization",
    20, 285,
  );

  doc.save("BlueZone_Recommended_Blood_Panel.pdf");
}
