/// scripts/bump-consent-version.ts
// Bumps NEXT_PUBLIC_CONSENT_VERSION (and POLICY/TERMS) in .env.local,
// writes a migration SQL file for consent_version_history, and inserts
// a record into that table via Supabase.
//
// Run:
//   npx ts-node -r tsconfig-paths/register \
//     --project tsconfig.scripts.json \
//     scripts/bump-consent-version.ts --reason "Updated research data types"

import * as fs   from "fs";
import * as path from "path";
import { createClient } from "@supabase/supabase-js";

// ── Arg parsing ───────────────────────────────────────────────────────────────

const args      = process.argv.slice(2);
const reasonIdx = args.indexOf("--reason");

if (reasonIdx === -1 || !args[reasonIdx + 1]) {
  console.error(
    'Usage: npx ts-node scripts/bump-consent-version.ts --reason "Your reason here"',
  );
  process.exit(1);
}

const reason = args[reasonIdx + 1];

// ── Parse .env.local ──────────────────────────────────────────────────────────

const ROOT     = process.cwd();
const ENV_PATH = path.join(ROOT, ".env.local");

if (!fs.existsSync(ENV_PATH)) {
  console.error(".env.local not found at", ENV_PATH);
  process.exit(1);
}

const envContent = fs.readFileSync(ENV_PATH, "utf-8");

/** Read a single key from env file content. Returns "" if not found. */
function getEnvVar(content: string, key: string): string {
  const match = content.match(new RegExp(`^${key}=(.*)$`, "m"));
  return match ? match[1].trim() : "";
}

/** Replace an existing key=value line, or append a new one. */
function setEnvVar(content: string, key: string, value: string): string {
  const regex = new RegExp(`^${key}=.*$`, "m");
  return regex.test(content)
    ? content.replace(regex, `${key}=${value}`)
    : `${content}\n${key}=${value}`;
}

// ── Version computation ───────────────────────────────────────────────────────

function computeNewVersion(current: string): string {
  const today = new Date().toISOString().slice(0, 10);           // YYYY-MM-DD
  const match = current.match(/^(\d{4}-\d{2}-\d{2})-v(\d+)$/);
  if (match && match[1] === today) {
    return `${today}-v${parseInt(match[2], 10) + 1}`;
  }
  return `${today}-v1`;
}

const currentVersion = getEnvVar(envContent, "NEXT_PUBLIC_CONSENT_VERSION");
const newVersion     = computeNewVersion(currentVersion);

// ── Update .env.local ─────────────────────────────────────────────────────────

let updated = envContent;
updated = setEnvVar(updated, "NEXT_PUBLIC_CONSENT_VERSION", newVersion);
updated = setEnvVar(updated, "NEXT_PUBLIC_POLICY_VERSION",  newVersion);
updated = setEnvVar(updated, "NEXT_PUBLIC_TERMS_VERSION",   newVersion);
fs.writeFileSync(ENV_PATH, updated, "utf-8");

// ── Create migration file ─────────────────────────────────────────────────────

const timestamp     = new Date().toISOString().replace(/\D/g, "").slice(0, 14);
const migrationsDir = path.join(ROOT, "supabase", "migrations");
const migrationPath = path.join(
  migrationsDir,
  `${timestamp}_consent_version_history.sql`,
);

const sql = `-- Auto-generated by scripts/bump-consent-version.ts
CREATE TABLE IF NOT EXISTS public.consent_version_history (
  id         UUID         DEFAULT gen_random_uuid() PRIMARY KEY,
  version    VARCHAR(20)  NOT NULL,
  reason     TEXT         NOT NULL,
  created_at TIMESTAMPTZ  DEFAULT NOW()
);
`;

fs.mkdirSync(migrationsDir, { recursive: true });
fs.writeFileSync(migrationPath, sql, "utf-8");

// ── Insert record into Supabase ───────────────────────────────────────────────

const supabaseUrl    = getEnvVar(envContent, "NEXT_PUBLIC_SUPABASE_URL");
const serviceRoleKey = getEnvVar(envContent, "SUPABASE_SERVICE_ROLE_KEY");

if (!supabaseUrl || !serviceRoleKey) {
  console.error(
    "Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local",
  );
  process.exit(1);
}

const supabase = createClient(supabaseUrl, serviceRoleKey, {
  auth: { persistSession: false },
});

(async () => {
  const { error } = await supabase
    .from("consent_version_history")
    .insert({ version: newVersion, reason });

  if (error) {
    console.error("Supabase insert failed:", error.message);
    process.exit(1);
  }

  console.log(`Consent version bumped to ${newVersion}. Reason: ${reason}`);
})().catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : String(err));
  process.exit(1);
});
