/// app/api/analysis/generate/route.ts
// POST: Run the full biomarker analysis pipeline (Stages 1–4) and persist
// the result to analysis_reports. Returns the full AnalysisResult as JSON.
//
// Optional body: { blood?: Partial<BloodPanel> }
//   Manual blood values are merged with DB biomarkers; manual takes precedence.

import { getServerSession }       from "next-auth";
import { authOptions }            from "@/lib/auth";
import { getAdminClient }         from "@/lib/supabase/admin";
import { TABLES, COLS }           from "@/lib/db/schema";
import {
  generateAnalysis,
}                                 from "@/lib/analysis/biomarker-engine";
import { isProtocolGated, getActiveCriticalEvents } from "@/lib/critical-values";
import type { UserHealthContextRow }                from "@/lib/types/health";
import type { AnalysisResult }    from "@/lib/analysis/biomarker-engine";
import { logApiUsage }            from "@/lib/ai/logApiUsage";
import {
  biomarkersToBloodPanel,
}                                 from "@/lib/analysis/types";
import type {
  BloodPanel,
  BiomarkerRow,
  CriticalFlag,
  UserProfile,
  WearableSnapshot,
  AnalysisInput,
}                                 from "@/lib/analysis/types";
import { Resend }                 from "resend";
import { NextRequest, NextResponse } from "next/server";
import { requireConsent }          from "@/middleware/requireConsent";
import {
  getPregnancyRulesForProduct,
  applyPregnancyGate,
  getPregnancyContextForNarrative,
  getMandatoryPregnancyDisclaimer,
} from "@/lib/pregnancy-safety";
import {
  getNutrientPairsForProtocol,
  applyCompetitionRules,
  generateTimingSchedule,
  getCompetitionNarrativeContext,
  type ProtocolProduct,
  type CompetitionResult,
  type TimingSlot,
} from "@/lib/nutrient-competition";
import {
  getBaselineContext,
  getBaselineNarrativeContext,
  type BaselineContext,
} from "@/lib/personal-baselines";

export const runtime     = "nodejs";
export const maxDuration = 120;

// Mirrored here so the disclaimer is always present even on early-exit errors.
const DISCLAIMER =
  "This analysis is generated by an AI system and is intended for informational and " +
  "health-optimisation purposes only. It does not constitute medical advice, diagnosis, " +
  "or treatment. Always consult a qualified healthcare professional before making changes " +
  "to your health regimen, supplementation, or medications.";

// ─────────────────────────────────────────────────────────────────────────────

export const POST = requireConsent(1)(async (req: NextRequest) => {
  // ── 1. Authenticate ───────────────────────────────────────────────────────
  const session = await getServerSession(authOptions);
  if (!session?.user?.id) {
    return NextResponse.json(
      { error: "Unauthorized", disclaimer: DISCLAIMER },
      { status: 401 },
    );
  }

  const userId    = session.user.id as string;
  const userEmail = (session.user.email as string | null) ?? null;
  const supabase  = getAdminClient();

  // ── Protocol gate check ────────────────────────────────────────────────────
  const { data: userCtx } = await supabase
    .from(TABLES.USER_HEALTH_CONTEXT)
    .select("protocol_gated_reason, protocol_gated_at, protocol_gate_acknowledged, pregnancy_status")
    .eq(COLS.USER_ID, userId)
    .maybeSingle();

  if (userCtx && isProtocolGated(userCtx as UserHealthContextRow)) {
    return NextResponse.json({
      gated:             true,
      gate_reason:       userCtx.protocol_gated_reason,
      gate_activated_at: userCtx.protocol_gated_at,
      recommendations:   [],
      critical_events:   await getActiveCriticalEvents(userId),
      disclaimer:        DISCLAIMER,
    }, { status: 403 });
  }
  // ── End gate check ─────────────────────────────────────────────────────────

  // ── Pregnancy safety context ──────────────────────────────────────────────
  const pregnancyStatus     = (userCtx as { pregnancy_status?: string | null } | null)?.pregnancy_status ?? "not_pregnant";
  const pregnancyContext    = getPregnancyContextForNarrative(pregnancyStatus);
  const pregnancyDisclaimer = getMandatoryPregnancyDisclaimer(pregnancyStatus);
  // ── End pregnancy safety context ─────────────────────────────────────────

  // ── 2. Parse optional manual blood override ───────────────────────────────
  let manualBlood: Partial<BloodPanel> = {};
  try {
    const body = await req.json();
    if (body?.blood && typeof body.blood === "object") {
      manualBlood = body.blood as Partial<BloodPanel>;
    }
  } catch {
    // empty or non-JSON body is fine — no manual override
  }

  // ── 3. Parallel DB fetch ──────────────────────────────────────────────────
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000)
    .toISOString()
    .slice(0, 10);

  const [biomarkersRes, wearableRes, prevReportRes, profileRes] = await Promise.all([
    // All biomarkers for this user, newest first (biomarkersToBloodPanel deduplicates)
    supabase
      .from(TABLES.BIOMARKERS)
      .select("name, value, unit, status, reference_min, reference_max")
      .eq(COLS.USER_ID, userId)
      .order(COLS.CREATED_AT, { ascending: false })
      .limit(60),

    // Most recent wearable snapshot within the last 7 days
    supabase
      .from(TABLES.WEARABLE_SNAPSHOTS)
      .select([
        COLS.SOURCE, COLS.DATE,
        COLS.HRV, COLS.RESTING_HR, COLS.SLEEP_SCORE,
        COLS.DEEP_SLEEP_MIN, COLS.REM_SLEEP_MIN,
        COLS.RECOVERY_SCORE, COLS.STRAIN_SCORE, COLS.READINESS_SCORE,
        COLS.STEPS, COLS.ACTIVE_CALORIES,
        COLS.HEART_RATE_AVG, COLS.HEART_RATE_MAX, COLS.HRV_RMSSD,
        COLS.SLEEP_TOTAL_MINUTES, COLS.SLEEP_REM_MINUTES,
        COLS.SLEEP_DEEP_MINUTES, COLS.SLEEP_LIGHT_MINUTES,
        COLS.VO2_MAX, COLS.STRESS_SCORE, COLS.SPO2,
      ].join(", "))
      .eq(COLS.USER_ID, userId)
      .gte(COLS.DATE, sevenDaysAgo)
      .order(COLS.DATE, { ascending: false })
      .limit(1)
      .maybeSingle(),

    // Previous successful report — used to compute longitudinal score delta
    supabase
      .from(TABLES.ANALYSIS_REPORTS)
      .select("id, payload, generated_at")
      .eq(COLS.USER_ID, userId)
      .eq(COLS.REPORT_TYPE, "biomarker_analysis")
      .eq(COLS.STATUS, "ready")
      .order(COLS.GENERATED_AT, { ascending: false })
      .limit(1)
      .maybeSingle(),

    // User profile — id IS the user id in this table (profiles.id → nextauth_users.id)
    supabase
      .from(TABLES.PROFILES)
      .select([
        COLS.AGE, COLS.BIOLOGICAL_SEX, COLS.HEIGHT_CM, COLS.WEIGHT_KG,
        COLS.ACTIVITY_LEVEL, COLS.CONDITIONS,
        COLS.CURRENT_MEDICATIONS, COLS.CURRENT_SUPPLEMENTS,
        COLS.BIOLOGICAL_AGE, COLS.USER_TIER,
      ].join(", "))
      .eq(COLS.ID, userId)
      .maybeSingle(),
  ]);

  const dbBiomarkers = (biomarkersRes.data ?? []) as BiomarkerRow[];

  type WRow = Record<string, number | string | null>;
  const wRow       = wearableRes.data   as WRow | null;
  const prevReport = prevReportRes.data as {
    id: string;
    payload: Record<string, unknown> | null;
    generated_at: string;
  } | null;
  const pRow = profileRes.data as Record<string, unknown> | null;

  // ── 4. Merge blood data (manual values override DB values) ─────────────────
  const dbBlood    = biomarkersToBloodPanel(dbBiomarkers);
  const bloodPanel: BloodPanel = { ...dbBlood, ...manualBlood };

  if (Object.keys(bloodPanel).length === 0) {
    return NextResponse.json(
      {
        error: "No biomarker data found — please upload a blood test first.",
        disclaimer: DISCLAIMER,
      },
      { status: 422 },
    );
  }

  // ── 5. Build AnalysisInput ────────────────────────────────────────────────
  // Helper: null → undefined coercions
  const toNum = (v: number | string | null | undefined): number | undefined =>
    typeof v === "number" ? v : undefined;
  const toStr = (v: number | string | null | undefined): string | undefined =>
    typeof v === "string" ? v : undefined;

  const wearable: WearableSnapshot | undefined = wRow
    ? {
        source:            toStr(wRow.source),
        date:              toStr(wRow.date),
        hrv:               toNum(wRow.hrv),
        restingHr:         toNum(wRow.resting_hr),
        sleepScore:        toNum(wRow.sleep_score),
        deepSleepMin:      toNum(wRow.deep_sleep_min),
        remSleepMin:       toNum(wRow.rem_sleep_min),
        recoveryScore:     toNum(wRow.recovery_score),
        strainScore:       toNum(wRow.strain_score),
        readinessScore:    toNum(wRow.readiness_score),
        steps:             toNum(wRow.steps),
        activeCalories:    toNum(wRow.active_calories),
        heartRateAvg:      toNum(wRow.heart_rate_avg),
        heartRateMax:      toNum(wRow.heart_rate_max),
        hrvRmssd:          toNum(wRow.hrv_rmssd),
        sleepTotalMinutes: toNum(wRow.sleep_total_minutes),
        sleepRemMinutes:   toNum(wRow.sleep_rem_minutes),
        sleepDeepMinutes:  toNum(wRow.sleep_deep_minutes),
        sleepLightMinutes: toNum(wRow.sleep_light_minutes),
        vo2Max:            toNum(wRow.vo2_max),
        stressScore:       toNum(wRow.stress_score),
        spo2:              toNum(wRow.spo2),
      }
    : undefined;

  const profile: UserProfile = {
    age:               typeof pRow?.age === "number" ? pRow.age : undefined,
    biologicalSex:     pRow?.biological_sex as "male" | "female" | "other" | undefined,
    heightCm:          typeof pRow?.height_cm === "number" ? pRow.height_cm : undefined,
    weightKg:          typeof pRow?.weight_kg === "number" ? pRow.weight_kg : undefined,
    activityLevel:     pRow?.activity_level as UserProfile["activityLevel"],
    conditions:        [
                         ...(pregnancyContext ? [`PREGNANCY SAFETY CONTEXT: ${pregnancyContext}`] : []),
                         ...(Array.isArray(pRow?.conditions) ? (pRow.conditions as string[]) : []),
                       ].length > 0
                         ? [
                             ...(pregnancyContext ? [`PREGNANCY SAFETY CONTEXT: ${pregnancyContext}`] : []),
                             ...(Array.isArray(pRow?.conditions) ? (pRow.conditions as string[]) : []),
                           ]
                         : undefined,
    currentMedications: typeof pRow?.current_medications === "string"
                          ? pRow.current_medications
                          : undefined,
    currentSupplements: typeof pRow?.current_supplements === "string"
                          ? pRow.current_supplements
                          : undefined,
    biologicalAge:     typeof pRow?.biological_age === "number"
                         ? pRow.biological_age
                         : undefined,
    userTier:          pRow?.user_tier === "advanced" ? "advanced" : "basic",
  };

  const analysisInput: AnalysisInput = { bloodPanel, wearable, profile };

  // ── 6. Run the full analysis pipeline ────────────────────────────────────
  const t0 = Date.now();
  let result: AnalysisResult;
  let usage: { stage2InputTokens: number; stage2OutputTokens: number; stage3InputTokens: number; stage3OutputTokens: number };
  let depthLevel: string;
  try {
    const run = await generateAnalysis(analysisInput);
    result     = run.result;
    usage      = run.usage;
    depthLevel = run.depth;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error("[analysis/generate] pipeline error user_id=<redacted>:", msg);
    return NextResponse.json(
      { error: "Analysis generation failed. Please try again.", disclaimer: DISCLAIMER },
      { status: 500 },
    );
  }
  const durationMs = Date.now() - t0;

  // ── Pregnancy supplement filter ───────────────────────────────────────────
  if (pregnancyStatus !== "not_pregnant") {
    const output = result as unknown as Record<string, unknown>;
    const schedule = output.supplementSchedule;
    if (Array.isArray(schedule)) {
      const filtered = (await Promise.all(
        (schedule as Array<Record<string, unknown>>).map(async (item) => {
          const category = String(item.supplement ?? item.name ?? "");
          const doseMg   = typeof item.dose_mg === "number" ? item.dose_mg : 0;
          const rules    = await getPregnancyRulesForProduct(category, pregnancyStatus);
          const gate     = applyPregnancyGate(category, rules, doseMg);
          if (gate.blocked) return null;
          if (gate.action === "dose_limit" && gate.dose_limit !== undefined) {
            return { ...item, dose_mg: gate.dose_limit };
          }
          return item;
        }),
      )).filter((x): x is Record<string, unknown> => x !== null);
      output.supplementSchedule = filtered;
    }
    if (pregnancyDisclaimer) {
      output.pregnancy_disclaimer = pregnancyDisclaimer;
    }
  }
  // ── End pregnancy supplement filter ──────────────────────────────────────

  // ── Nutrient competition layer ─────────────────────────────────────────────
  const compPayload  = result as unknown as Record<string, unknown>;
  const compSchedule = Array.isArray(compPayload.supplementSchedule)
    ? (compPayload.supplementSchedule as Array<Record<string, unknown>>)
    : [];
  const protocolProducts: ProtocolProduct[] = compSchedule
    .map((item) => ({
      supplement: String(item.supplement ?? item.name ?? ""),
      dose_mg:    typeof item.dose_mg === "number" ? item.dose_mg : undefined,
    }))
    .filter((p) => !!p.supplement);
  const competitionRules   = await getNutrientPairsForProtocol(
    protocolProducts.map((p) => p.supplement),
  );
  const competitionResults = applyCompetitionRules(competitionRules, protocolProducts);
  const timingSchedule     = generateTimingSchedule(competitionResults, protocolProducts);
  const criticalConflicts  = competitionResults.filter((r) => r.clinical_significance === "critical");
  compPayload.competition_narrative = getCompetitionNarrativeContext(competitionResults);
  compPayload.competition_conflicts = competitionResults;
  compPayload.timing_schedule       = timingSchedule;
  const synergyNotes = competitionResults
    .filter((r) => r.action === "suggest_addition")
    .map((r) => `Consider recommending ${r.nutrient_b} — user is taking ${r.nutrient_a} which creates a synergy dependency.`);
  if (synergyNotes.length > 0) {
    compPayload.synergy_suggestions = synergyNotes;
  }
  // ── End nutrient competition layer ────────────────────────────────────────

  // ── Personal baseline context ──────────────────────────────────────────────
  const markerNames = dbBiomarkers.map((b) => b.name as string);
  let baselineContexts: BaselineContext[] = [];
  if (markerNames.length > 0) {
    try {
      baselineContexts = await getBaselineContext(userId, markerNames);
      const baselineNarrative = getBaselineNarrativeContext(baselineContexts);
      if (baselineNarrative) {
        compPayload.baseline_narrative = baselineNarrative;
      }
    } catch (err) {
      console.error("[analysis/generate] baseline context error:", err instanceof Error ? err.message : err);
    }
  }
  // ── End personal baseline context ─────────────────────────────────────────

  // ── 7. Persist result to analysis_reports ─────────────────────────────────
  const previousScore =
    typeof prevReport?.payload?.overallScore === "number"
      ? prevReport.payload.overallScore
      : null;

  const inputSnapshot = {
    biomarkerCount:   dbBiomarkers.length,
    hasManualBlood:   Object.keys(manualBlood).length > 0,
    hasWearable:      !!wearable,
    dataCompleteness: result.dataCompleteness,
    previousReportId: prevReport?.id ?? null,
    previousScore,
    scoreDelta: previousScore !== null ? result.overallScore - previousScore : null,
    durationMs,
  };

  const { data: savedReport, error: insertErr } = await supabase
    .from(TABLES.ANALYSIS_REPORTS)
    .insert({
      [COLS.USER_ID]:        userId,
      [COLS.REPORT_TYPE]:    "biomarker_analysis",
      [COLS.STATUS]:         "ready",
      [COLS.PAYLOAD]:        result,
      [COLS.MODEL]:          "claude-sonnet-4-20250514",
      [COLS.INPUT_SNAPSHOT]: inputSnapshot,
      [COLS.GENERATED_AT]:   result.generatedAt,
    })
    .select(COLS.ID)
    .maybeSingle();

  if (insertErr) {
    // Non-fatal: still return the result — don't block on a DB write failure
    console.error(
      "[analysis/generate] DB insert error user_id=<redacted>:",
      insertErr.message,
    );
  }

  const reportId = (savedReport as { id: string } | null)?.id ?? null;

  // ── 8. Log API usage (fire-and-forget) ────────────────────────────────────
  const totalInputTokens  = usage.stage2InputTokens  + usage.stage3InputTokens;
  const totalOutputTokens = usage.stage2OutputTokens + usage.stage3OutputTokens;
  // claude-sonnet-4: $3.00/MTok input, $15.00/MTok output
  const totalCostUsd = totalInputTokens * 0.000003 + totalOutputTokens * 0.000015;

  logApiUsage({
    userId,
    endpoint:           "/api/analysis/generate",
    model:              "claude-sonnet-4-20250514",
    inputTokens:        totalInputTokens,
    outputTokens:       totalOutputTokens,
    durationMs,
    reportId:           reportId ?? undefined,
    stage2InputTokens:  usage.stage2InputTokens,
    stage2OutputTokens: usage.stage2OutputTokens,
    stage3InputTokens:  usage.stage3InputTokens,
    stage3OutputTokens: usage.stage3OutputTokens,
    totalCostUsd,
    depthLevel,
    dataCompleteness:   result.dataCompleteness,
  });

  // ── 9. Critical flag email (seek_care_today urgency only) ─────────────────
  const urgentFlags: CriticalFlag[] = result.criticalFlags.filter(
    (f) => f.urgency === "seek_care_today",
  );

  if (urgentFlags.length > 0 && userEmail) {
    sendCriticalFlagEmail(userEmail, urgentFlags, result.disclaimer).catch((err) => {
      console.error(
        "[analysis/generate] critical-flag email failed:",
        err instanceof Error ? err.message : err,
      );
    });
  }

  // ── 10. Return full result ────────────────────────────────────────────────
  return NextResponse.json({
    ...result,
    reportId,
    competition_conflicts: competitionResults,
    timing_schedule:       timingSchedule,
    critical_conflicts:    criticalConflicts,
    baseline_context:      baselineContexts,
    ...(pregnancyDisclaimer ? { pregnancy_disclaimer: pregnancyDisclaimer } : {}),
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Email helper
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Send a plain-language email for every critical flag with urgency
 * "seek_care_today". Called fire-and-forget — errors are logged, not thrown.
 */
async function sendCriticalFlagEmail(
  to:         string,
  flags:      CriticalFlag[],
  disclaimer: string,
): Promise<void> {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    console.warn(
      "[analysis/generate] RESEND_API_KEY not set — skipping critical flag email",
    );
    return;
  }

  const from   = process.env.EMAIL_FROM ?? "onboarding@resend.dev";
  const resend = new Resend(apiKey);

  const flagLines = flags
    .map(
      (f) =>
        `• ${f.marker}${f.value ? ` (${f.value})` : ""}\n` +
        `  What this means: ${f.concern}\n` +
        `  Recommended action: ${f.action}`,
    )
    .join("\n\n");

  const text =
    `Your Blue Zone health analysis has identified the following signal(s) that ` +
    `warrant prompt medical attention:\n\n` +
    `${flagLines}\n\n` +
    `We strongly recommend consulting your physician or a qualified healthcare ` +
    `professional as soon as possible. Do not adjust medications or supplements ` +
    `based on this report without speaking to your doctor first.\n\n` +
    `---\n` +
    `${disclaimer}`;

  await resend.emails.send({ from, to, subject: "Blue Zone: Important health signal detected", text });
}
