/// components/landing/MethodologyStatement.tsx
"use client";

import { Shield, BookOpen, FlaskConical } from "lucide-react";
import { motion } from "framer-motion";

export function MethodologyStatement() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-80px" }}
      transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
      style={{ maxWidth: 672, margin: "0 auto", padding: "48px 16px" }}
    >
      <div style={{ background: "#111118", border: "1px solid rgba(255,255,255,0.05)", borderRadius: 16, padding: 32 }}>
        <div className="flex flex-col md:flex-row md:gap-6">
          {/* Icon */}
          <div className="mb-4 md:mb-0 flex-shrink-0">
            <Shield size={20} style={{ color: "var(--ion-blue)" }} />
          </div>
          {/* Content */}
          <div style={{ flex: 1 }}>
            {/* Eyebrow */}
            <div style={{ fontSize: 10, letterSpacing: "0.2em", textTransform: "uppercase" as const, color: "var(--ion-blue)", opacity: 0.6, fontFamily: "var(--font-ui,'Inter',sans-serif)", marginBottom: 12 }}>
              HOW PROTOCOLS ARE GENERATED
            </div>
            {/* Heading */}
            <h3 style={{ fontFamily: "var(--font-serif,'Syne',sans-serif)", fontSize: 18, fontWeight: 600, color: "#FFFFFF", marginBottom: 12 }}>
              Research-based logic. Not a language model.
            </h3>
            {/* Body paragraphs */}
            <p style={{ fontSize: 14, color: "rgba(255,255,255,0.55)", fontFamily: "var(--font-ui,'Inter',sans-serif)", lineHeight: 1.7, marginBottom: 12 }}>
              Each protocol is generated by a rule engine built on peer-reviewed exercise physiology and sports medicine literature — not by prompting an AI and hoping it gets it right.
            </p>
            <p style={{ fontSize: 14, color: "rgba(255,255,255,0.55)", fontFamily: "var(--font-ui,'Inter',sans-serif)", lineHeight: 1.7, marginBottom: 12 }}>
              Biomarker thresholds are calibrated against athletic reference ranges, not standard population norms. A ferritin of 62 ng/mL is flagged differently for an endurance athlete in high training load than for a sedentary adult.
            </p>
            <p style={{ fontSize: 14, color: "rgba(255,255,255,0.55)", fontFamily: "var(--font-ui,'Inter',sans-serif)", lineHeight: 1.7, marginBottom: 0 }}>
              Supplement recommendations are cross-referenced against known interactions, training-phase timing, and absorption variables before they reach your protocol.
            </p>
            {/* Footer */}
            <div style={{ borderTop: "1px solid rgba(255,255,255,0.05)", paddingTop: 20, marginTop: 20, display: "flex", gap: 24, flexWrap: "wrap" as const }}>
              <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                <BookOpen size={14} style={{ color: "rgba(255,255,255,0.3)", flexShrink: 0 }} />
                <span style={{ fontSize: 12, color: "rgba(255,255,255,0.4)", fontFamily: "var(--font-ui,'Inter',sans-serif)" }}>
                  Built on exercise physiology &amp; sports medicine research
                </span>
              </div>
              <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                <FlaskConical size={14} style={{ color: "rgba(255,255,255,0.3)", flexShrink: 0 }} />
                <span style={{ fontSize: 12, color: "rgba(255,255,255,0.4)", fontFamily: "var(--font-ui,'Inter',sans-serif)" }}>
                  Athletic reference ranges — not population norms
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </motion.div>
  );
}
